### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by koutsie** [lorpus/abaddon#8]
Is this planned or?

**Comment by lorpus** [comment]
i dont see why it shouldnt work on linux. i just dont have build instructions since im not super familiar with building stuff for linux

**Comment by koutsie** [comment]
Ahaa, time to test building it then.
I thought this had some os dependant parts.

**Comment by lorpus** [comment]
lemme know how it goes im curious

**Comment by koutsie** [comment]
I abaddon trying because of VCpkg.
